// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Customer
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Address { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string CustomerType { get; set; }

    public string CompanyName { get; set; }

    public string TaxCode { get; set; }

    public Guid? AssignedTo { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee AssignedToNavigation { get; set; }

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual User User { get; set; }
}