// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Employee
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string EmployeeCode { get; set; }

    public string Position { get; set; }

    public string Department { get; set; }

    public decimal? Salary { get; set; }

    public DateOnly? HireDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();

    public virtual User User { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}