// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Quotation
{
    public Guid Id { get; set; }

    public string QuotationCode { get; set; }

    public Guid CustomerId { get; set; }

    public Guid VehicleId { get; set; }

    public int? Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}