// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class Vehicle
{
    public Guid Id { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int Year { get; set; }

    public decimal Price { get; set; }

    public string Color { get; set; }

    public string Status { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Employee CreatedByNavigation { get; set; }

    public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();
}